apiVersion: example.com.my.domain/v1beta1
kind: VisitorsApp
metadata:
  name: visitorsapp-sample
spec:
  backendSize: 1
  backendAutoScaling: false
  backendServiceNodePort: 30685
  frontendTitle: "visitors app"
  frontendSize: 1
  frontendAutoScaling: false
  frontendServiceNodePort: 30686
